/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck da API */
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar registros de auditoria do sistema com filtros e paginação (ADMIN e MANAGER) */
        get: operations["AuditController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar detalhes de um registro de auditoria por ID (ADMIN e MANAGER) */
        get: operations["AuditController_findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Conexão em tempo real via Server-Sent Events (SSE)
         * @description Mantém um canal HTTP persistente (EventSource) para notificar o frontend instantaneamente.
         */
        get: operations["NotificationController_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter dados da empresa (tenant) da sessão atual */
        get: operations["TenantController_getCurrentTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualizar dados da empresa (exclusivo para Administradores) */
        patch: operations["TenantController_updateCurrentTenant"];
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter dados do usuário da sessão atual */
        get: operations["UserController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar colaboradores da mesma empresa (ADMIN e MANAGER) */
        get: operations["UserController_listUsers"];
        put?: never;
        /** Criar novo colaborador na empresa atual (Restrito a ADMIN) */
        post: operations["UserController_createEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remover um colaborador da empresa (Restrito a ADMIN) */
        delete: operations["UserController_removeEmployee"];
        options?: never;
        head?: never;
        /** Atualizar dados de um colaborador (Restrito a ADMIN) */
        patch: operations["UserController_updateEmployee"];
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auto-cadastro: cria a Empresa (Tenant) e o usuário ADMIN */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autenticar com email e senha (emite cookies HttpOnly e Bearer) */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redireciona para autenticação com Google */
        get: operations["AuthController_googleAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback da autenticação com Google */
        get: operations["AuthController_googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redireciona para autenticação com GitHub */
        get: operations["AuthController_githubAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback da autenticação com GitHub */
        get: operations["AuthController_githubCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register-oauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Conclui o cadastro da empresa após login social (Google ou GitHub) */
        post: operations["AuthController_registerOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renovar Access Token via Refresh Token (cookie ou body) */
        post: operations["AuthController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerrar sessão, revogar refresh token e limpar cookies */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Importar clientes em massa via arquivo CSV */
        post: operations["CustomerManagementController_importCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar clientes da empresa atual (com busca opcional) */
        get: operations["CustomerManagementController_findAll"];
        put?: never;
        /** Cadastrar novo cliente na empresa atual */
        post: operations["CustomerManagementController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar cliente por ID */
        get: operations["CustomerManagementController_findById"];
        put?: never;
        post?: never;
        /** Remover um cliente (Restrito a ADMIN e MANAGER) */
        delete: operations["CustomerManagementController_remove"];
        options?: never;
        head?: never;
        /** Atualizar dados de um cliente */
        patch: operations["CustomerManagementController_update"];
        trace?: never;
    };
    "/carriers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todas as transportadoras */
        get: operations["carrierController_findAll"];
        put?: never;
        /** Cadastrar nova transportadora */
        post: operations["carrierController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carriers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar transportadora por ID */
        get: operations["carrierController_findById"];
        put?: never;
        post?: never;
        /** Remover transportadora */
        delete: operations["carrierController_remove"];
        options?: never;
        head?: never;
        /** Atualizar transportadora */
        patch: operations["carrierController_update"];
        trace?: never;
    };
    "/freight/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simular frete considerando peso, cubagem, distância e seguro
         * @description Calcula cotações de frete comparando todas as transportadoras ativas da empresa e grava auditoria.
         */
        post: operations["FreightController_simulate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/freight/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar histórico de simulações de frete realizadas na empresa */
        get: operations["FreightController_getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/freight/reports/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar geração assíncrona de relatório de histórico de fretes
         * @description Enfileira a exportação em background via BullMQ. O frontend será avisado via SSE assim que o arquivo estiver disponível.
         */
        post: operations["FreightReportController_exportReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/freight/reports/download/{fileName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fazer download de um relatório CSV gerado pelo worker */
        get: operations["FreightReportController_downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditLogPaginatedResponseDto: {
            data: {
                id: string;
                tenantId?: string | null;
                userId?: string | null;
                userName?: string | null;
                userEmail?: string | null;
                /** @enum {string} */
                action: "AUTH_LOGIN" | "AUTH_LOGOUT" | "USER_CREATE" | "USER_UPDATE" | "USER_ROLE_CHANGE" | "USER_DELETE" | "CARRIER_CREATE" | "CARRIER_UPDATE" | "CARRIER_DELETE" | "CUSTOMER_CREATE" | "CUSTOMER_UPDATE" | "CUSTOMER_DELETE";
                resource: string;
                resourceId?: string | null;
                ipAddress?: string | null;
                userAgent?: string | null;
                details?: {
                    [key: string]: unknown;
                } | null;
                createdAt: string;
            }[];
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        AuditLogDetailResponseDto: {
            id: string;
            tenantId?: string[];
            userId?: string[];
            /** @enum {string} */
            action: "AUTH_LOGIN" | "AUTH_LOGOUT" | "USER_CREATE" | "USER_UPDATE" | "USER_ROLE_CHANGE" | "USER_DELETE" | "CARRIER_CREATE" | "CARRIER_UPDATE" | "CARRIER_DELETE" | "CUSTOMER_CREATE" | "CUSTOMER_UPDATE" | "CUSTOMER_DELETE";
            resource: string;
            resourceId?: string[];
            ipAddress?: string[];
            userAgent?: string[];
            details?: {
                [key: string]: unknown;
            } | null;
            createdAt: string;
        };
        TenantResponseDto: {
            id: string;
            name: string;
            document: string;
            status: string;
            createdAt: string;
            updatedAt: string;
        };
        UpdateTenantDto: {
            name?: string;
            document?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "SUSPENDED";
        };
        UserResponseDto: {
            id: string;
            name: string;
            email: string;
            role: string;
            tenantId: string;
            authProvider?: string;
            createdAt?: string;
            updatedAt?: string;
        };
        CreateUserDto: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            /**
             * @default OPERATOR
             * @enum {string}
             */
            role?: "ADMIN" | "MANAGER" | "OPERATOR";
        };
        UpdateUserDto: {
            name?: string;
            /** Format: email */
            email?: string;
            /** @enum {string} */
            role?: "ADMIN" | "MANAGER" | "OPERATOR";
            password?: string;
        };
        MessageResponseDto: {
            message: string;
        };
        RegisterTenantDto: {
            companyName: string;
            document: string;
            adminName: string;
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponseDto: {
            user?: {
                id: string;
                name: string;
                email: string;
                role: string;
                tenantId: string;
                authProvider?: string;
                createdAt?: string;
                updatedAt?: string;
            };
            accessToken?: string;
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterOAuthTenantDto: {
            onboardingToken: string;
            companyName: string;
            document: string;
        };
        RefreshTokenDto: {
            refreshToken?: string;
        };
        CustomerImportResponseDto: {
            totalProcessed: number;
            totalImported: number;
            errors: {
                row: number;
                error: string;
            }[];
        };
        CreateCustomerDto: {
            name: string;
            cpf: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            zipCode?: string | null;
            street?: string | null;
            number?: string | null;
            complement?: string | null;
            city?: string | null;
            state?: string | null;
        };
        CustomerResponseDto: {
            id: string;
            name: string;
            email?: string[];
            cpf: string;
            phone?: string[];
            zipCode?: string[];
            street?: string[];
            number?: string[];
            complement?: string[];
            city?: string[];
            state?: string[];
            tenantId: string;
            createdAt: string;
            updatedAt: string;
        };
        UpdateCustomerDto: {
            name?: string;
            cpf?: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            zipCode?: string | null;
            street?: string | null;
            number?: string | null;
            complement?: string | null;
            city?: string | null;
            state?: string | null;
        };
        CreateCarrierDto: {
            name: string;
            document: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            /** @default 0 */
            basePrice?: number;
            /** @default 0 */
            pricePerKg?: number;
            /** @default 3 */
            deadlineDays?: number;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
        };
        CarrierResponseDto: {
            id: string;
            tenantId: string;
            name: string;
            document: string;
            email?: string[];
            phone?: string[];
            basePrice: string;
            pricePerKg: string;
            deadlineDays: number;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            createdAt: string;
            updatedAt: string;
        };
        UpdateCarrierDto: {
            name?: string;
            document?: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            /** @default 0 */
            basePrice?: number;
            /** @default 0 */
            pricePerKg?: number;
            /** @default 3 */
            deadlineDays?: number;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
        };
        CarrierMessageResponseDto: {
            message: string;
        };
        SimulateFreightDto: {
            destinationZipCode: string;
            originZipCode?: string;
            weight: number;
            dimensions: {
                length: number;
                width: number;
                height: number;
            };
            declaredValue: number;
            /** Format: uuid */
            carrierId?: string;
        };
        SimulateFreightResponseDto: {
            origin: {
                zipCode: string;
                city: string;
                state: string;
                isEstimated?: boolean;
            };
            destination: {
                zipCode: string;
                city: string;
                state: string;
                isEstimated?: boolean;
            };
            package: {
                actualWeightKg: number;
                volumetricWeightKg: number;
                chargedWeightKg: number;
                declaredValue: number;
                dimensions: {
                    length: number;
                    width: number;
                    height: number;
                };
            };
            /** @enum {string} */
            deliveryType: "LOCAL" | "STATE" | "INTERSTATE";
            quotes: {
                carrierId: string;
                carrierName: string;
                deadlineDays: number;
                breakdown: {
                    basePrice: number;
                    pricePerKg: number;
                    chargedWeightKg: number;
                    weightCost: number;
                    distanceMultiplier: number;
                    shippingSubtotal: number;
                    insuranceCost: number;
                };
                totalPrice: number;
            }[];
        };
        FreightHistoryResponseDto: {
            data: {
                id: string;
                tenantId: string;
                userId: string | null;
                originZipCode: string;
                destinationZipCode: string;
                originCity: string | null;
                originState: string | null;
                destinationCity: string | null;
                destinationState: string | null;
                actualWeightKg: string;
                volumetricWeightKg: string;
                chargedWeightKg: string;
                declaredValue: string;
                dimensionsLength: string;
                dimensionsWidth: string;
                dimensionsHeight: string;
                /** @enum {string} */
                deliveryType: "LOCAL" | "STATE" | "INTERSTATE";
                cheapestCarrierId: string | null;
                cheapestCarrierName: string | null;
                cheapestPrice: string | null;
                cheapestDeadlineDays: number | null;
                quotes: {
                    carrierId: string;
                    carrierName: string;
                    deadlineDays: number;
                    breakdown: {
                        basePrice: number;
                        pricePerKg: number;
                        chargedWeightKg: number;
                        weightCost: number;
                        distanceMultiplier: number;
                        shippingSubtotal: number;
                        insuranceCost: number;
                    };
                    totalPrice: number;
                }[];
                createdAt: string;
            }[];
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        ExportFreightReportDto: {
            /**
             * @default csv
             * @enum {string}
             */
            format?: "csv";
            startDate?: string;
            endDate?: string;
            /** @default 1000 */
            limit?: number;
        };
        ExportReportResponseDto: {
            jobId?: string;
            status: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retorna mensagem de status da API */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AuditController_findAll: {
        parameters: {
            query?: {
                action?: "AUTH_LOGIN" | "AUTH_LOGOUT" | "USER_CREATE" | "USER_UPDATE" | "USER_ROLE_CHANGE" | "USER_DELETE" | "CARRIER_CREATE" | "CARRIER_UPDATE" | "CARRIER_DELETE" | "CUSTOMER_CREATE" | "CUSTOMER_UPDATE" | "CUSTOMER_DELETE";
                resource?: string;
                userId?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de registros de auditoria com dados do usuário */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPaginatedResponseDto"];
                };
            };
        };
    };
    AuditController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalhes do registro de auditoria */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogDetailResponseDto"];
                };
            };
        };
    };
    NotificationController_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantController_getCurrentTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados da empresa vinculada ao usuário logado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponseDto"];
                };
            };
        };
    };
    TenantController_updateCurrentTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantDto"];
            };
        };
        responses: {
            /** @description Empresa atualizada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponseDto"];
                };
            };
        };
    };
    UserController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados do perfil do usuário autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UserController_listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de usuários do tenant atual */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    UserController_createEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description Colaborador cadastrado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UserController_removeEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Colaborador removido com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    UserController_updateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description Colaborador atualizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterTenantDto"];
            };
        };
        responses: {
            /** @description Empresa e Administrador cadastrados com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login bem-sucedido com cookies emitidos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_githubAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_githubCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_registerOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterOAuthTenantDto"];
            };
        };
        responses: {
            /** @description Empresa e Administrador criados via OAuth com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Sessão renovada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout efetuado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    CustomerManagementController_importCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Arquivo CSV com os dados dos clientes
                     */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Resultado da importação em lote com contadores e erros */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerImportResponseDto"];
                };
            };
        };
    };
    CustomerManagementController_findAll: {
        parameters: {
            query?: {
                /** @description Filtrar por nome, CPF ou e-mail */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de clientes do tenant atual */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponseDto"][];
                };
            };
        };
    };
    CustomerManagementController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerDto"];
            };
        };
        responses: {
            /** @description Cliente cadastrado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponseDto"];
                };
            };
        };
    };
    CustomerManagementController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados detalhados do cliente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponseDto"];
                };
            };
        };
    };
    CustomerManagementController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cliente removido com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    CustomerManagementController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerDto"];
            };
        };
        responses: {
            /** @description Cliente atualizado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponseDto"];
                };
            };
        };
    };
    carrierController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de transportadoras da empresa */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierResponseDto"][];
                };
            };
        };
    };
    carrierController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCarrierDto"];
            };
        };
        responses: {
            /** @description Transportadora cadastrada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierResponseDto"];
                };
            };
        };
    };
    carrierController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados detalhados da transportadora */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierResponseDto"];
                };
            };
        };
    };
    carrierController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transportadora removida com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierMessageResponseDto"];
                };
            };
        };
    };
    carrierController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCarrierDto"];
            };
        };
        responses: {
            /** @description Transportadora atualizada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierResponseDto"];
                };
            };
        };
    };
    FreightController_simulate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateFreightDto"];
            };
        };
        responses: {
            /** @description Cotações de frete calculadas com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateFreightResponseDto"];
                };
            };
        };
    };
    FreightController_getHistory: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Histórico paginado de simulações de frete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FreightHistoryResponseDto"];
                };
            };
        };
    };
    FreightReportController_exportReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportFreightReportDto"];
            };
        };
        responses: {
            /** @description A geração do relatório foi enfileirada com sucesso */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportReportResponseDto"];
                };
            };
        };
    };
    FreightReportController_downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Nome do arquivo retornado na notificação */
                fileName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Arquivo CSV para download */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
}
